SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `vuecafe`.`board`;
SET FOREIGN_KEY_CHECKS = 1;
INSERT INTO `vuecafe`.`board` (`user_id`, `subject`, `content`, `hit`)
SELECT
  CASE
    WHEN n % 3 = 0 THEN 'admin'
    WHEN n % 3 = 1 THEN 'test1'
    ELSE 'test2'
  END AS user_id,
  CONCAT('Sample Subject ', n) AS subject,
  CONCAT('Sample content for article number ', n, '.') AS content,
  FLOOR(RAND() * 100) AS hit
FROM (
  SELECT @rownum := @rownum + 1 AS n
  FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
     (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
     (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
     (SELECT @rownum := 1) r
  LIMIT 500
) nums;

